### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by RakeshShresthaNP** [castle-engine/quickjs-demo#1]
Is this project dead? It has been very long that there are no updates ..

**Comment by michaliskambi** [comment]
That's for @Coldzer0 to answer. Admittedly this is not on my priority now.

**Comment by Coldzer0** [comment]
> Is this project dead? It has been very long that there are no updates ..

Sorry, I didn't notice your question.

I have been very busy lately ( Building my own company ^_^ )

But No, the project is not dead I was rewriting the code base to support the full engine to be usable from JS code.
If you are in the Discord server I can share my progress for now and if you want to contribute to it that would be great.

**Comment by barefists** [comment]
Just to add my name to the list of people interested in this project. :)

I have an unhealthy obsession with js game engines that are not HTML based.

**Comment by Coldzer0** [comment]
I've created a new branch called full_translation

https://github.com/castle-engine/quickjs-demo/tree/full_translation

This branch contains the translation units for some classes (not fully converted to JS)

However, I plan to use the latest FPC Trunk version and the Extended RTTI to reimplement the Native Classes to JS.
It should make the process easier and better than translating everything by hand.
